### ISSUE TITLE
With a similar setup, would this secure a local webserver exposed to the internet?

### ISSUE THREAD

**Issue by chicago-joe** [francoisruty/fruty_docker-outbound-restriction#1]
i.e. versus running ngrok with a custom dns;

**Comment by francoisruty** [comment]
Hello, this setup purpose is to restrict outbound traffic from your server, except what you explicitly allow. I don't know what you mean by "securing a local webserver", but if by securing you mean "adding an additional layer of security so that in the event someone manages to execute code on my server at least this code cannot communicate over the network", yes this setup can be useful
